from . import start
from . import question_admin_support
from . import admin_support
from . import hemis_file
from . import faculty_location
from . import akademic_file
from . import payment_file
from . import learner
from . import help
from . import echo
